
export const UPDATE_UNPACKED_ITEMS_FILTER = 'UPDATE_UNPACKED_ITEMS_FILTER';
export const UPDATE_PACKED_ITEMS_FILTER = 'UPDATE_PACKED_ITEMS_FILTER';

export const UPDATE_NEW_ITEM_VALUE = 'UPDATE_NEW_ITEM_VALUE';
export const CLEAR_NEW_ITEM_VALUE = 'CLEAR_NEW_ITEM_VALUE';

export const UPDATE_COUNTDOWN = 'UPDATE_COUNTDOWN';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const UPDATE_ALL_ITEMS = 'UPDATE_ALL_ITEMS';

export const SET_NEW_ITEM = 'SEND_NEW_ITEM';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const TOGGLE_ITEM_REQUEST = 'TOGGLE_ITEM_REQUEST';
export const TOGGLE_ITEM = 'TOGGLE_ITEM';

export const MARK_ALL_AS_UNPACKED_REQUEST = 'MARK_ALL_AS_UNPACKED_REQUEST';
export const MARK_ALL_AS_UNPACKED = 'MARK_ALL_AS_UNPACKED';